# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\desktop\项目\掌控板测试软件\MpythonTest_7001\MpythonTest_7001\startHmi.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_startHmi(object):
    def setupUi(self, startHmi):
        startHmi.setObjectName("startHmi")
        startHmi.resize(306, 171)
        self.gridLayout = QtWidgets.QGridLayout(startHmi)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(startHmi)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.combo_project = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_project.sizePolicy().hasHeightForWidth())
        self.combo_project.setSizePolicy(sizePolicy)
        self.combo_project.setMinimumSize(QtCore.QSize(0, 25))
        self.combo_project.setObjectName("combo_project")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.combo_project.addItem("")
        self.horizontalLayout.addWidget(self.combo_project)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.combo_stage = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_stage.sizePolicy().hasHeightForWidth())
        self.combo_stage.setSizePolicy(sizePolicy)
        self.combo_stage.setMinimumSize(QtCore.QSize(0, 25))
        self.combo_stage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.combo_stage.setObjectName("combo_stage")
        self.combo_stage.addItem("")
        self.combo_stage.addItem("")
        self.horizontalLayout_2.addWidget(self.combo_stage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.button_confirm = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_confirm.sizePolicy().hasHeightForWidth())
        self.button_confirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.button_confirm.setFont(font)
        self.button_confirm.setObjectName("button_confirm")
        self.verticalLayout.addWidget(self.button_confirm)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.code_lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.code_lineEdit.setObjectName("code_lineEdit")
        self.horizontalLayout_4.addWidget(self.code_lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.key_lineEdit = QtWidgets.QLineEdit(self.page_2)
        self.key_lineEdit.setObjectName("key_lineEdit")
        self.horizontalLayout_5.addWidget(self.key_lineEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.code_btn = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.code_btn.sizePolicy().hasHeightForWidth())
        self.code_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.code_btn.setFont(font)
        self.code_btn.setObjectName("code_btn")
        self.horizontalLayout_6.addWidget(self.code_btn)
        self.login_btn = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_6.addWidget(self.login_btn)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(startHmi)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(startHmi)

    def retranslateUi(self, startHmi):
        _translate = QtCore.QCoreApplication.translate
        startHmi.setWindowTitle(_translate("startHmi", " "))
        self.label.setText(_translate("startHmi", "项目: "))
        self.combo_project.setItemText(0, _translate("startHmi", "7001_讯飞实验箱_小学版"))
        self.combo_project.setItemText(1, _translate("startHmi", "7001_讯飞实验箱_初中版"))
        self.combo_project.setItemText(2, _translate("startHmi", "7005_掌控板_学境"))
        self.combo_project.setItemText(3, _translate("startHmi", "7005_模块_学境"))
        self.combo_project.setItemText(4, _translate("startHmi", "7007_掌控板_单板"))
        self.combo_project.setItemText(5, _translate("startHmi", "7009_乐动掌控2.0"))
        self.combo_project.setItemText(6, _translate("startHmi", "SN绑定MAC地址"))
        self.combo_project.setItemText(7, _translate("startHmi", "TS260_信息科技示教板"))
        self.combo_project.setItemText(8, _translate("startHmi", "TS260_掌控板"))
        self.label_2.setText(_translate("startHmi", "阶段: "))
        self.combo_stage.setItemText(0, _translate("startHmi", "半成品测试"))
        self.combo_stage.setItemText(1, _translate("startHmi", "成品测试"))
        self.button_confirm.setText(_translate("startHmi", "确定"))
        self.label_5.setText(_translate("startHmi", "使用软件前请将机器码复制给到 辰奕智能-何浩\n"
"获取密钥后填写到密钥输入框然后点击注册使用"))
        self.label_3.setText(_translate("startHmi", "机器码:"))
        self.label_4.setText(_translate("startHmi", "密钥:  "))
        self.code_btn.setText(_translate("startHmi", "复制机器码"))
        self.login_btn.setText(_translate("startHmi", "注册"))

